<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hitesh-Mac-Mini.local" name="com.eduven.testcase.NetworkRelatedTestCases" tests="6" failures="1" timestamp="26 Jul 2016 11:55:51 GMT" time="587.028" errors="1">
  <testcase name="install_app_and_language_selection_test" time="193.619" classname="com.eduven.testcase.NetworkRelatedTestCases"/>
  <testcase name="swicth_lingo_related_connectivity_test" time="226.723" classname="com.eduven.testcase.NetworkRelatedTestCases"/>
  <testcase name="check_evMenu_for_network_connection_test" time="21.019" classname="com.eduven.testcase.NetworkRelatedTestCases">
    <failure type="java.lang.AssertionError" message="Error Message!!Connectivity related issue not coming. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Error Message!!Connectivity related issue not coming. expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.eduven.utils.Reusables.verifyElementEnable(Reusables.java:351)
	at com.eduven.utils.Reusables.verifyConnectionRelatedError(Reusables.java:840)
	at com.eduven.testcase.NetworkRelatedTestCases.check_evMenu_for_network_connection_test(NetworkRelatedTestCases.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.eduven.utils.RunTestng.main(RunTestng.java:57)
]]>
    </failure>
  </testcase> <!-- check_evMenu_for_network_connection_test -->
  <testcase name="test_network_turnon_network_connection_test" time="58.948" classname="com.eduven.testcase.NetworkRelatedTestCases"/>
  <testcase name="purchase_app_related_connectivity_test" time="30.984" classname="com.eduven.testcase.NetworkRelatedTestCases">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.eduven.modules.EntityDetailPage.getPurchaseBtnInstance(EntityDetailPage.java:49)
	at com.eduven.modules.EntityDetailPage.navigateToPurchasePage(EntityDetailPage.java:70)
	at com.eduven.testcase.NetworkRelatedTestCases.purchase_app_related_connectivity_test(NetworkRelatedTestCases.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.eduven.utils.RunTestng.main(RunTestng.java:57)
]]>
    </error>
  </testcase> <!-- purchase_app_related_connectivity_test -->
  <testcase name="test_network_turnoff_network_connection_test" time="55.735" classname="com.eduven.testcase.NetworkRelatedTestCases"/>
</testsuite> <!-- com.eduven.testcase.NetworkRelatedTestCases -->
